# EmbedResources.cmake -- the RCDATA resources of a Windows .rc file as C data,
# for the builds without Windows resources (Linux, Android). Every line
#     NAME RCDATA "path"
# of RC becomes an entry of g_ot_resources (OtResource, platform/win32_compat.h),
# which FindResourceA / LoadResource / LockResource / SizeofResource read there.
#
#   cmake -DRC=<configured .rc> -DOUT=<file.c> -P EmbedResources.cmake

if(NOT RC OR NOT OUT)
    message(FATAL_ERROR "EmbedResources.cmake: RC and OUT are required")
endif()

file(STRINGS "${RC}" lines REGEX "^[A-Za-z_][A-Za-z0-9_]*[ \t]+RCDATA[ \t]+\"")
set(body "")
set(table "")
set(n 0)
foreach(line IN LISTS lines)
    string(REGEX MATCH "^([A-Za-z_][A-Za-z0-9_]*)[ \t]+RCDATA[ \t]+\"([^\"]+)\"" _ "${line}")
    set(name "${CMAKE_MATCH_1}")
    set(path "${CMAKE_MATCH_2}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "EmbedResources.cmake: ${name}: ${path} not found")
    endif()
    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")
    # Two hex digits -> "0x..,"; 32 bytes a line.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x..,){32})" "\\1\n    " bytes "${bytes}")
    string(APPEND body "static const unsigned char r_${name}[${size} + 1] = {\n    ${bytes}0x00\n};\n")
    string(APPEND table "    { \"${name}\", r_${name}, ${size}u },\n")
    math(EXPR n "${n} + 1")
endforeach()

file(WRITE "${OUT}.tmp"
"/* Generated by port/cmake/EmbedResources.cmake from ${RC}: do not edit. */\n"
"typedef struct OtResource { const char *name; const unsigned char *data; unsigned size; } OtResource;\n\n"
"${body}\n"
"const OtResource g_ot_resources[] = {\n${table}    { 0, 0, 0 }\n};\n"
"const unsigned g_ot_resources_n = ${n}u;\n")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
