#!/usr/bin/env python3
"""smaa_glsl_embed.py - xboxrecomp/src/d3d/gles/gles_smaa_src.h from smaa/SMAA.hlsl.

The OpenGL ES renderer (gles/gles_post.c) compiles SMAA.hlsl as GLSL ES 3.00 (SMAA_GLSL_3) and needs it as a C string:
the file without its comments (its licence is kept at the top of the header) and without blank lines.

    python3 xboxrecomp/tools/smaa_glsl_embed.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
D3D = os.path.join(HERE, '..', 'src', 'd3d')
SRC = os.path.join(D3D, 'smaa', 'SMAA.hlsl')
OUT = os.path.join(D3D, 'gles', 'gles_smaa_src.h')

text = open(SRC, encoding='latin-1').read()          # (a few Latin-1 characters in its comments)
licence = re.match(r'\s*(/\*\*.*?\*/)', text, re.S).group(1)
body = re.sub(r'/\*.*?\*/', '', text, flags=re.S)          # block comments
body = re.sub(r'//[^\n]*', '', body)                         # line comments
lines = [l.rstrip() for l in body.split('\n')]
lines = [l for l in lines if l.strip()]

def c_str(line):
    return '"' + line.replace('\\', '\\\\').replace('"', '\\"') + '\\n"'

with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
    f.write('/* gles_smaa_src.h - SMAA by Jorge Jimenez et al. (https://www.iryoku.com/smaa/), MIT licence below.\n')
    f.write(' * GENERATED by xboxrecomp/tools/smaa_glsl_embed.py from ../smaa/SMAA.hlsl without its comments. Do not edit. */\n')
    f.write(licence + '\n')
    f.write('static const char k_smaa_src[] =\n')
    for l in lines:
        f.write('    ' + c_str(l) + '\n')
    f.write('    ;\n')
print(OUT, len(lines), 'lines')
